env:
  browser: true
  commonjs: true
  es6: true
extends:
  - seek
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  project: ./tsconfig.json
rules: {}
